### ISSUE TITLE
C++ implementation

### ISSUE THREAD

**Issue by gavanderhoorn** [AIS-Bonn/opt_control#1]
Thanks for making this available.

Just to avoid duplication of effort: would you perhaps already have a C/C++ implementation of this?

**Comment by MariusBeul** [comment]
Hi,
a C/C++ ROS implementation is in the pipeline and hopefully available next
week.

Best
Marius

Am Fr., 17. Aug. 2018 um 21:26 Uhr schrieb G.A. vd. Hoorn <
notifications@github.com>:

**Comment by gavanderhoorn** [comment]
That is very nice to hear.

I'll be looking forward to that.

**Comment by jettan** [comment]
This is a very nice thing to hear. I'm also looking forward to the C++ release.

**Comment by facontidavide** [comment]
It would be nice if this C++ implementation comes without ROS "baked-in", i.e. if there is a clear separation between the C++ library and the ROS wrapper.

Cheers

**Comment by MariusBeul** [comment]
The ROS C++ implementation is now available.
The static library can be used without the ROS wrapper.

**Comment by facontidavide** [comment]
I don't want to sound ungrateful, but a binary file and generated headers is not what we meant. I guess it is a first step, though

**Comment by gavanderhoorn** [comment]
@MariusBeul: thanks for this.

Could you clarify what sort of system you used to compile the static library?

@facontidavide: it is indeed a very good first step as it provides a very nice "ground truth" for anyone wishing to do a completely stand-alone implementation in whatever language without having to have access to a matlab license.

**Comment by MariusBeul** [comment]
@gavanderhoorn The library was compiled for 'Intel->x86-64 (Linux 64)'

**Comment by mabl** [comment]
It is really unfortunate that no truely free implementation is provided. But I guess having a reference is better than nothing. Is there anyone working actively on an implementation?
