### ISSUE TITLE
Source code or windows lib

### ISSUE THREAD

**Issue by olivierp99** [AIS-Bonn/opt_control#13]
Hello,

would it be possible to have the source code or a lib for windows?

Thank you

**Comment by MariusBeul** [comment]
Hi, unfortunately currently I can not provide the source nor a windows library. The mex however is compiles for windows as well as linux.

**Comment by MariusBeul** [comment]
We rebranded the package with the name "TopiCo". Now the sources are available!

https://github.com/AIS-Bonn/TopiCo

**Comment by olivierp9** [comment]
thank you!
