### ISSUE TITLE
I can't run this code properly

### ISSUE THREAD

**Issue by pp-user** [AIS-Bonn/opt_control#8]
>> example
Invalid MEX-file 'C:\Users\pc\Desktop\Just Do It\one_iros\opt_control-master\matlab\opt_control_lib_mex.mexw64': The specified module could not be found.

error example (line 173)
[J_setp_struct,solution_out,T_waypoints,P,V,A,J,t] =
opt_control_lib_mex(State_start,Waypoints,V_max,V_min,A_max,A_min,J_max,J_min,A_global,b_comp_global,b_sync_V,b_sync_A,b_sync_J,b_sync_W,b_rotate,b_best_solution,b_hard_vel_limit,b_catch_up,solution_in,ts_rollout);

How to solve this problem？

**Comment by MariusBeul** [comment]
Hello pp-user,

which MATLAB-version are you using and which OS are you running it on? I assume windows 10?

**Comment by pp-user** [comment]
I use Matlab2014，and my computer is running on windows7 64bits&nbsp;



发自我的iPhone


------------------ Original ------------------

**Comment by MariusBeul** [comment]
Hello pp-user,

sorry for the long delay. The MATLAB library is compiled for MATLAB 2019 and can thus not be run under MATLAB 2014. See https://de.mathworks.com/help/matlab/matlab_external/version-compatibility.html
