### ISSUE TITLE
"Could not find valid timed solution!" on Ubuntu, but works on Windows

### ISSUE THREAD

**Issue by ShrimpGumbo** [AIS-Bonn/opt_control#9]
Hi!
Thanks for the great package!
I am running into a problem though that I would like to ask you about.
I'm playing around with a python script (using the Matlab python engine) that uses a function modifying your example.m to calculate trajectories (see attached files).
When I run it on Windows (Windows 10, Matlab R2019b Update 3) it works properly, but when I use exactly the same file on Ubuntu 16.04 (and 18.04) I get the error posted in the header. I also tested the configuration in Matlab directly on Ubuntu (without python) and I get the same error.

Is there any difference between both .mex files that might cause these issues? Do you have any recommendation how to go forward, because originally Linux is my preferred OS.

Thanks for your support!
Best Regards!

[IssuedFiles.zip](https://github.com/AIS-Bonn/opt_control/files/4159416/IssuedFiles.zip)

**Comment by MariusBeul** [comment]
Hello ShrimpGumbo, thank you for posting this issue. To my knowledge, there exist no difference between the versions. Can you please provide all the input data that causes this error?
`State_start, Waypoints, V_max, V_min, A_max, A_min, J_max, J_min, A_global, b_comp_global, b_sync_V, b_sync_A, b_sync_J, b_sync_W, b_rotate, b_best_solution, b_hard_vel_limit, b_catch_up, solution_in, ts_rollout`

Thank you!

**Comment by MariusBeul** [comment]
Hello ShrimpGumbo,

can you please check again with our newly released package: https://github.com/AIS-Bonn/TopiCo

Best,
Marius
